# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('sold', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whsales_listing_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=7)),
                ('wormhole_class', models.PositiveIntegerField()),
                ('shattered', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whsales.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Wormhole',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lifetime', models.PositiveIntegerField()),
                ('mass', models.PositiveIntegerField()),
                ('jumpable', models.PositiveIntegerField()),
                ('destination', models.CharField(choices=[(b'Class 1', b'Class 1'), (b'Class 2', b'Class 2'), (b'Class 3', b'Class 3'), (b'Class 4', b'Class 4'), (b'Class 5', b'Class 5'), (b'Class 6', b'Class 6'), (b'Class 13', b'Class 13'), (b'High-Sec', b'High-Sec'), (b'Low-Sec', b'Low-Sec'), (b'Null-Sec', b'Null-Sec'), (b'Thera', b'Thera'), (b'Barbican', b'Barbican'), (b'Conflux', b'Conflux'), (b'Redoubt', b'Redoubt'), (b'Sentinel', b'Sentinel'), (b'Vidette', b'Vidette')], max_length=8)),
                ('regenerate', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='statics',
            field=models.ManyToManyField(blank=True, to='whsales.Wormhole'),
        ),
        migrations.AddField(
            model_name='listing',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whsales.System'),
        ),
    ]
