# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 14:53
from __future__ import unicode_literals

from django.db import migrations
import csv
import os

def read_csv(name, delimiter=","):
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), name)) as f:
        reader = csv.DictReader(f, delimiter=str(delimiter))
        data = []
        for row in reader:
            data.append(row)
    return data

def generate_systems(apps, schema_editor):
    System = apps.get_model('whsales', 'System')
    Effect = apps.get_model('whsales', 'Effect')
    data = read_csv('systems.csv')
    for s in data:
        print "Creating " + s['solarSystemName']
        clean_data = {}
        clean_data['id'] = int(s['solarSystemID'])
        clean_data['name'] = s['solarSystemName']
        clean_data['wormhole_class'] = int(s['class'])
        clean_data['shattered'] = bool(s['shattered'])
        effect = s.pop('effect', None)
        if not effect:
            effect = "None"
        model = System.objects.update_or_create(id=clean_data['id'], defaults=clean_data)[0]
        if effect:
            model.effect = Effect.objects.get_or_create(name=effect)[0]
            model.save()

def delete_systems(apps, schema_editor):
    System = apps.get_model('whsales', 'System')
    System.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('whsales', '0002_wormholes'),
    ]

    operations = [
        migrations.RunPython(generate_systems, delete_systems)
    ]
