# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whsales', '0004_statics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wormhole_class', models.PositiveIntegerField(blank=True, null=True)),
                ('shattered', models.BooleanField(default=False)),
                ('offering', models.PositiveIntegerField(help_text=b'Million ISK')),
                ('notes', models.TextField(blank=True, null=True)),
                ('fulfilled', models.DateTimeField(blank=True, null=True)),
                ('_statics', models.ManyToManyField(blank=True, to='whsales.Wormhole')),
                ('effect', models.ManyToManyField(blank=True, to='whsales.Effect')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whsales_wanted_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whsales.System')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(help_text=b'Million ISK'),
        ),
    ]
